In [2]:
import numpy as np
import pandas as pd
import datetime
import json
from sklearn import linear_model

In [38]:
import os
import socket

if os.name != "nt":
    import fcntl
    import struct

    def get_interface_ip(ifname):
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        return socket.inet_ntoa(fcntl.ioctl(s.fileno(), 0x8915, struct.pack('256s',
                                ifname[:15]))[20:24])

def get_lan_ip():
    ip = socket.gethostbyname(socket.gethostname())
    if ip.startswith("127.") and os.name != "nt":
        interfaces = [
            "eth0",
            "eth1",
            "eth2",
            "wlan0",
            "wlan1",
            "wifi0",
            "ath0",
            "ath1",
            "ppp0",
            ]
        for ifname in interfaces:
            try:
                ip = get_interface_ip(ifname)
                break
            except IOError:
                pass
    return ip

In [8]:
actual=pd.read_csv("file.csv")
actual.dropna(inplace=True)
actual.head()

   DAY_NUM  DAY  SLOT1  SLOT2  SLOT3  SLOT4  SLOT5  SLOT6
0        0    0     69   92.0  293.0  368.0  353.0    1.0
1        1    1     90  120.0   96.0   69.0   29.0  109.0
2        2    2     87   32.0  116.0    1.0   89.0  121.0
3        3    3     96   69.0    1.0   89.0  121.0   96.0

In [39]:
    a=np.random.randint(low=1000, high=1500, size=100)
    #slot 5
    b=np.random.randint(low=1000, high=1200, size=100)
    #slot 6
    c=np.random.randint(low=800,high=1000,size=100)
    #slot 3
    d=np.random.randint(low=600,high=900,size=100)
    #slot 1
    e=np.random.randint(low=400,high=700,size=100)
    #slot 2
    f=np.random.randint(low=200,high=500,size=100)

    arr=np.array([e,f,d,a,b,c])
    data=pd.DataFrame(columns=["DAY_NUM","DAY","SLOT1","SLOT2","SLOT3","SLOT4","SLOT5","SLOT6"])
    data["DAY_NUM"]=np.arange(100)
    days=np.arange(7)
    for i in range(14):
        days=np.append(arr=days,values=np.arange(7))
    days=days[:100]    
    data["DAY"]=days
    data["SLOT1"]=e
    data["SLOT2"]=f
    data["SLOT3"]=d
    data["SLOT4"]=a
    data["SLOT5"]=b
    data["SLOT6"]=c
    x=np.array([]);
    for i in range(6):
        x=np.append(arr=a,values=data.iloc[0, 2:][i])
    
    now = datetime.datetime.now()
    hour=now.hour
    if (hour>=23 and hour<24) or (hour>0 and hour<3):
        slot=1
        from_time=3
    if hour>=3 and hour<7:
        slot=2
        from_time=7
    if hour>=7 and hour<11:
        slot=3
        from_time=11
    if hour>=11 and hour<15:
        slot=4
        from_time=15
    if hour>=15 and hour<19:
        slot=5
        from_time=19
    if hour>=19 and hour<23:
        slot=0
        from_time=23
        
    
    baseurl=get_lan_ip()+"/img"
    graphing=[0,0,0,0,0,0]
    a=[0,0,0,0,0,0]
    x=0
    nextday=0
    r=http.request('GET','http://localhost/max_bidding.php')
    js=json.loads(r.data)
    for j in js:
        print(j['time'])
    for i in range(6):
        train_x=np.array(data.iloc[:70,1])
        train_y=np.array(data.iloc[:70,2+slot])
        test=data.iloc[70:,1]
        import datetime
        model=linear_model.LinearRegression()
        train_x=train_x.reshape(-1,1)
        test=test.reshape(-1,1)
        model.fit(train_x,train_y)
        day=now.strftime("%w")
        y=model.predict(np.array(int(day)+nextday).reshape(-1,1))
        graphing[x]=y[0]
        for j in js:
#             print(j['time'])
            if j['time']==from_time:
                a[x]={"fromTime":from_time,"toTime":(from_time+4)%24,"urlImage":baseurl+str(slot)+".png","estTraffic":y[0],"maxBid":j['max_bid'],"minBid":j['min_bid']}
        from_time=from_time+4
        if(from_time>24):
            from_time=from_time%24
        if slot == 5:
            slot=-1
            nextday=1
        slot=slot+1
        x=x+1

    for i in range(6):
        colors=['g']*(i)+['b']+['g']*(6-i-1)
        dfs=pd.DataFrame(graphing)
        ax=dfs.plot(kind='bar',color=colors)
        img=ax.get_figure()
        img.savefig("img"+str(i)+".png")

23
3
7
11
15
19
23
3
7
11
15
19
23
3
7
11
15
19
23
3
7
11
15
19
23
3
7
11
15
19
23
3
7
11
15
19
23
3
7
11
15
19

/Users/ronaksakhuja/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:69: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
/Users/ronaksakhuja/anaconda/lib/python3.6/site-packages/matplotlib/pyplot.py:523: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)

In [34]:
a

[0, 0, 0, 0, 0, 0]

In [20]:
json.dumps(a)

'[{"fromTime": 23, "toTime": 3, "urlImage": "192.168.43.189/img0.png", "estTraffic": 544.3892857142857}, {"fromTime": 3, "toTime": 7, "urlImage": "192.168.43.189/img1.png", "estTraffic": 359.0035714285714}, {"fromTime": 7, "toTime": 11, "urlImage": "192.168.43.189/img2.png", "estTraffic": 727.6142857142856}, {"fromTime": 11, "toTime": 15, "urlImage": "192.168.43.189/img3.png", "estTraffic": 1255.4857142857145}, {"fromTime": 15, "toTime": 19, "urlImage": "192.168.43.189/img4.png", "estTraffic": 1104.3249999999998}, {"fromTime": 19, "toTime": 23, "urlImage": "192.168.43.189/img5.png", "estTraffic": 906.4071428571428}]'

In [9]:
data

    DAY_NUM  DAY  SLOT1  SLOT2  SLOT3  SLOT4  SLOT5  SLOT6
0         0    0    422    245    625   1182   1178    975
1         1    1    576    398    872   1323   1015    824
2         2    2    681    397    871   1231   1095    878
3         3    3    540    235    825   1046   1156    844
4         4    4    420    448    852   1008   1155    839
5         5    5    631    256    612   1377   1153    871
6         6    6    467    220    803   1112   1119    848
7         7    0    599    213    771   1142   1082    970
8         8    1    605    430    658   1087   1176    989
9         9    2    508    309    758   1199   1119    845
10       10    3    488    478    851   1412   1060    925
11       11    4    673    460    812   1404   1151    812
12       12    5    597    466    669   1276   1127    890
13       13    6    504    320    827   1135   1060    810
14       14    0    419    331    633   1425   1001    830
15       15    1    458    252    707   1113   1072    826
16       16    2    594    302    867   1063   1030    925
17       17    3    410    333    809   1211   1154    847
18       18    4    663    203    878   1045   1124    922
19       19    5    623    209    701   1059   1044    836
20       20    6    522    201    704   1045   1008    842
21       21    0    663    395    824   1285   1115    904
22       22    1    589    221    723   1477   1121    952
23       23    2    604    407    875   1359   1096    893
24       24    3    474    304    801   1109   1168    837
25       25    4    501    327    867   1405   1116    902
26       26    5    668    252    657   1473   1184    875
27       27    6    657    253    864   1438   1179    836
28       28    0    548    235    818   1113   1085    805
29       29    1    449    331    736   1380   1198    825
..      ...  ...    ...    ...    ...    ...    ...    ...
70       70    0    404    345    868   1464   1098    922
71       71    1    572    214    660   1307   1071    823
72       72    2    698    493    614   1051   1000    859
73       73    3    563    478    793   1378   1191    891
74       74    4    574    211    781   1373   1021    809
75       75    5    405    231    650   1100   1019    946
76       76    6    696    491    667   1447   1109    983
77       77    0    643    230    843   1360   1099    800
78       78    1    699    392    658   1081   1134    926
79       79    2    676    344    805   1456   1077    820
80       80    3    631    468    695   1097   1114    946
81       81    4    505    481    863   1253   1008    854
82       82    5    541    248    826   1339   1070    850
83       83    6    610    237    794   1221   1148    918
84       84    0    419    377    833   1474   1003    841
85       85    1    418    252    629   1120   1031    810
86       86    2    456    261    899   1011   1049    971
87       87    3    641    322    611   1444   1108    859
88       88    4    666    313    745   1418   1197    925
89       89    5    668    425    758   1457   1194    996
90       90    6    515    383    881   1227   1149    896
91       91    0    694    362    640   1492   1141    811
92       92    1    429    392    734   1443   1025    967
93       93    2    588    259    636   1254   1127    824
94       94    3    596    336    890   1320   1012    925
95       95    4    524    256    800   1471   1111    817
96       96    5    621    410    777   1190   1191    801
97       97    6    614    290    834   1160   1115    801
98       98    0    583    410    807   1304   1024    837
99       99    1    461    203    762   1379   1081    851

[100 rows x 8 columns]

In [12]:
import urllib3

In [13]:
http = urllib3.PoolManager()

In [14]:
r = http.request('GET', 'http://localhost/max_bidding.php')

In [27]:
r.status

200

In [17]:
js=json.loads(r.data)

In [22]:
for j in js:
    if j['time']=='23':
        print(j)

{'ID': '1', 'time': '23', 'max_bid': '0', 'min_bid': '2500'}

In [27]:
now = datetime.datetime.now()
hour=now.hour
(hour>=23 and hour<24) or (hour>0 and hour<3)

True